export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_ERROR = 'USER_ERROR'

export const WORD_TRANSLATE = 'WORD_TRANSLATE'
export const WORD_TRANSLATE_ADD = 'WORD_TRANSLATE_ADD'
export const CHOOSE_LANGUAGE_ON = 'CHOOSE_LANGUAGE_ON'
export const CLOSE_LANGUAGE_MODAL = 'CLOSE_LANGUAGE_MODAL'
export const SET_LANGUAGE_FROM = 'SET_LANGUAGE_FROM'
export const SET_LANGUAGE_TO = 'SET_LANGUAGE_TO'

export const GET_WORDS_VOCABULARY = 'GET_WORDS_VOCABULARY'

