export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_ERROR = 'USER_ERROR'

export const WORD_TRANSLATE = 'WORD_TRANSLATE'
export const WORD_TRANSLATE_ADD = 'WORD_TRANSLATE_ADD'

export const GET_WORDS_VOCABULARY = 'GET_WORDS_VOCABULARY'